---

- name: Install setuptools
  apt: state=installed pkg=python-setuptools

- name: Install rpi.gpio
  shell: easy_install rpi.gpio
  sudo: yes

- name: Copy test script
  copy: src=../files/test-mcp3008.py dest=/home/pi mode=0755 owner=pi group=pi
