---
# Initialization w/WIFI adapted with gratitude from https://github.com/scottmotte/ansible-pi.git
- name: 'Configure WIFI'
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Update APT package cache'
  apt: upgrade=safe update_cache=yes

- name: 'Reboot'
  command: /sbin/reboot -t now
